apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-prometheus-appset
spec:
  generators:
  - list:
      elements:
      - cluster: docker-k8s
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'kube-prometheus-{{cluster}}'
    spec:
      project: local-project
      source:
        repoURL: https://github.com/carlos-ffs/confluent-dremio-fluentbit-logs.git
        targetRevision: HEAD
        path: charts/prometheus
        helm:
          valueFiles: 
          - values.yaml
      destination:
        server: '{{url}}'
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true  # Automatically delete resources that no longer exist in Git
          selfHeal: true  # Automatically sync if drift is detected
          allowEmpty: false  # Allows deleting all resources when they are no longer in Git
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
  syncPolicy:
    preserveResourcesOnDeletion: true