{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: catalog-minio-secret
type: Opaque
stringData:
  awsAccessKeyId: {{ (index .Values.minio.svcaccts 0).accessKey }}
  awsSecretAccessKey: {{ (index .Values.minio.svcaccts 0).secretKey }}
{{- end }}