apiVersion: v1
kind: Secret
metadata:
  name: catalog-minio-secret
type: Opaque
stringData:
  awsAccessKeyId: {{ .Values.minio.svcaccts[0].accessKey }}
  awsSecretAccessKey: {{ .Values.minio.svcaccts[0].secretKey }}