# Oldest quay robot. Less than 2weeks to expire.
apiVersion: v1
kind: Secret
metadata:
  name: dremio-pull-secret
data:
  .dockerconfigjson: <YOUR_BASE64_ENCODED_DOCKER_CONFIG_JSON>
type: kubernetes.io/dockerconfigjson