apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: argocd-all-components-monitor
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchLabels:
      app.kubernetes.io/part-of: argocd
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_label_app_kubernetes_io_name
          targetLabel: component
          action: replace
