apiVersion: v2
name: minio
description: High Performance Object Storage
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: minio
    version: "5.4.0"
    repository: https://charts.min.io/
