apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-loki
  labels:
    grafana_datasource: "1"        # tells the sideâ€‘car to load this
data:
  loki.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-stack-docker-k8s.monitoring.svc.cluster.local:3100
        isDefault: false
        version: 1
