apiVersion: v1
kind: Secret
metadata:
  name: kafka-sasl-users
type: Opaque
stringData:
  plain-users.json: |
    {
        "fluent-bit-user": "fluent-bit-producer-secret",
        "test-user": "test-password"
    }