apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: fluent-bit
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  partitionCount: 1
  configs:
    cleanup.policy: "delete"
  kafkaClusterRef:
    name: kafka