apiVersion: v1
kind: Secret
metadata:
  name: credential
type: Opaque
stringData:
  plain-users.json: |
    {
      "fluent-bit-user": "fluent-bit-producer-secret",
      "test-user": "test-password",
      "kafka_client": "kafka_client-secret",
      "kafka": "kafka-secret"
    }
  plain.txt: |
    username=kafka
    password=kafka-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: file-secret
type: Opaque
stringData:
  userstore.txt: |
    testuser1:password1
    testuser2:password2
    kafka:kafka-secret
    sr:sr-secret
    krp:krp-secret
    connect:connect-secret
    c3:c3-secret
    ksql:ksql-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: mds-client
type: Opaque
stringData:
  bearer.txt: |
    username=kafka
    password=kafka-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: c3-mds-client
type: Opaque
stringData:
  bearer.txt: |
    username=c3
    password=c3-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: connect-mds-client
type: Opaque
stringData:
  bearer.txt: |
    username=connect
    password=connect-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: sr-mds-client
type: Opaque
stringData:
  bearer.txt: |
    username=sr
    password=sr-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: ksqldb-mds-client
type: Opaque
stringData:
  bearer.txt: |
    username=ksql
    password=ksql-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: krp-mds-client
type: Opaque
stringData:
  bearer.txt: |
    username=krp
    password=krp-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: rest-credential
type: Opaque
stringData:
  bearer.txt: |
    username=kafka
    password=kafka-secret