fluent-bit:
  enabled: true
  config:
    outputs: |
      [OUTPUT]
          name kafka
          match *
          brokers kafka.confluent.svc.cluster.local:9092
          topics fluent-bit
          rdkafka.security.protocol SASL_SSL
          rdkafka.sasl.mechanism PLAIN
          rdkafka.sasl.username fluent-bit-user
          rdkafka.sasl.password fluent-bit-producer-secret
          rdkafka.enable.ssl.certificate.verification false