apiVersion: v1
kind: Secret
metadata:
  name: priv-repo-confluent-dremio-flink-logs
  namespace: argocd
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: https://github.com/carlos-ffs/confluent-dremio-flink-logs.git
  password: <password>
  username: <usernae>